Add a lock icon to covariant menu
It seems like there is something amiss with vector-icons. I get the
following error when the lock-option.js is imported in a test:

(that's why the lock-option and covariant-menu tests have had to be
removed)

node_modules/@expo/vector-icons/build/AntDesign.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createIconSet from './createIconSet';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (../../node_modules/@expo/vector-icons/src/Icons.ts:1:1)